spring:
  profiles:
    active: ${PROFILE}

---
#---------------------------------------------------
#            GLOBAL CONFIGURATION
#---------------------------------------------------

info:
  name: Projet Annuel
app:
  description: ${info.name} est une application pour l'ESGI, groupe[Alvin, Maxime, Vincent]
spring:
  application:
    name: Hotel
application:
  version: 1.0
server:
  port: 8080
  contextPath: /

logging:
  level:
    org:
      springframework:
        web: DEBUG
        hibernate: DEBUG

booking:
  timezone: "Africa/Libreville"

path.default.generator.file: classpath:/files/
default.price.festive.room: 10000


spring.mail.path.file.attachement: classpath:/files/confirmation_reservation.pdf

# VELOCITY TEMPLATES
spring.velocity.resource-loader-path: classpath:/templates/velocity

# JPA  - USE this to generate table
spring.jpa.generate-ddl: true

---
#---------------------------------------------------
#            DEVELOPER  MODE
#---------------------------------------------------
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  jmx:
    enabled: true
# H2 (acces with localhost:port/h2 or localhost:port/h2-console/)
  h2:
    console:
      enabled: true
      path: /h2
# Datasource( The database URL jdbc:h2:~/test opens the database test in your user home directory)
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver


# Mailing (download fakeSMTP, and run with java -jar fakeSMTP.jar )
mail:
  protocol: smtp
  smtp:
    host: localhost
    port: 2505
  support:
    username: test
    password: test
  template.path.logo: src\main\resources\static\img\logoRHM.png
  template:
    url:
      home: http://residencedeshautsdemenaye.com/
      unsubscribe: http://residencedeshautsdemenaye.com/api/mail/unsubscribe/



---
#---------------------------------------------------
#            TEST  MODE
#---------------------------------------------------
spring:
  profiles: test
  jpa:
    show-sql: true
  jmx:
    enabled: true
server:
  port: 8080

# H2 (acces with localhost:port/h2 or localhost:port/h2-console/)
  h2:
    console:
      enabled: true
      path: /h2
# Datasource( The database URL jdbc:h2:~/test opens the database test in your user home directory)
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

# Use GrrenMail (cf: http://www.icegreen.com/greenmail/)
mail:
  protocol: smtp
  smtp:
    host: localhost
    port: 9999
  support:
    username: test
    password: test
  template.path.logo: src\main\resources\static\img\logoRHM.png
  template:
    url:
      home: http://residencedeshautsdemenaye.com/
      unsubscribe: http://residencedeshautsdemenaye.com/api/mail/unsubscribe/


---
#---------------------------------------------------
#            PRODUCTION  MODE
#---------------------------------------------------


spring:
  profiles: prod
  datasource:
    username: oxisyzbsanalxj
    password: 2fbb453cf023e8d93f4f620684df36f41e55854e3633406fc3cb81c9bad04ac7
    url: postgres://oxisyzbsanalxj:2fbb453cf023e8d93f4f620684df36f41e55854e3633406fc3cb81c9bad04ac7@ec2-54-247-189-141.eu-west-1.compute.amazonaws.com:5432/d6eoh07c8lsg6r
    maxActive: 10
    maxIdle: 5
    min-idle: 2
    initialSize: 5
    removeAbandoned: true
    platform: d6eoh07c8lsg6r
    max-wait: 10000
    test-on-borrow: true
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
  jmx:
    enabled: true
server:
  port: 0

# Mailing
mail:
  protocol: smtp
  smtp:
    host: smtp.gmail.com
    port: 587
  support:
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}

