spring:
  profiles:
    active: ${PROFILE:"dev"}

---
#---------------------------------------------------
#            GLOBAL CONFIGURATION
#---------------------------------------------------

info:
  name: Projet Annuel
app:
  description: ${info.name} est une application pour l'ESGI, groupe[Alvin, Maxime, Vincent]
spring:
  application:
    name: Hotel
application:
  version: 1.0
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG
        hibernate: DEBUG

booking:
  timezone: "Africa/Libreville"



spring.mail.path.file.attachement: classpath:/files/confirmation_reservation.pdf

# VELOCITY TEMPLATES
<<<<<<< HEAD
#spring.velocity.resource-loader-path: classpath:/templates/velocity
=======
spring.velocity.resource-loader-path: classpath:/templates/velocity
>>>>>>> fixe, update, and add h2 database for dev mode, configure postgresql heroku database

# JPA  - USE this to generate table
spring.jpa.generate-ddl: true

---
#---------------------------------------------------
#            DEVELOPER  MODE
#---------------------------------------------------
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jmx:
    enabled: true
# H2 (acces with localhost:port/h2 or localhost:port/h2-console/)
  h2:
    console:
      enabled: true
      path: /h2
# Datasource( The database URL jdbc:h2:~/test opens the database test in your user home directory)
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver


# Mailing (download fakeSMTP, and run with java -jar fakeSMTP.jar )
mail:
  protocol: smtp
  smtp:
    host: localhost
    port: 2505
  support:
    username: test
    password: test



---
#---------------------------------------------------
#            TEST  MODE
#---------------------------------------------------
spring:
  profiles: test
  jpa:
    show-sql: true
  jmx:
    enabled: true
server:
  port: 8080

# H2 (acces with localhost:port/h2 or localhost:port/h2-console/)
  h2:
    console:
      enabled: true
      path: /h2
# Datasource( The database URL jdbc:h2:~/test opens the database test in your user home directory)
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

# Mailing (download fakeSMTP, and run with java -jar fakeSMTP.jar )
mail:
  protocol: smtp
  smtp:
    host: localhost
    port: 2505
  support:
    username: test
    password: test


---
#---------------------------------------------------
#            PRODUCTION  MODE
#---------------------------------------------------


spring:
  profiles: prod
  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    url: ${DATABASE_URL}
    maxActive: 10
    maxIdle: 5
    min-idle: 2
    initialSize: 5
    removeAbandoned: true
    platform: d6eoh07c8lsg6r
    max-wait: 10000
    test-on-borrow: true
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
  jmx:
    enabled: true
server:
  port: 0

# Mailing
mail:
  protocol: smtp
  smtp:
    host: smtp.gmail.com
    port: 587
  support:
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}

